apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: dspenard-playground
    cnrm.cloud.google.com/state-into-spec: merge
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"compute.cnrm.cloud.google.com/v1beta1","kind":"ComputeHealthCheck","metadata":{"annotations":{},"name":"test-conf-conn-backend-healthcheck","namespace":"test-conf-conn-negs"},"spec":{"checkIntervalSec":10,"httpHealthCheck":{"port":80},"location":"global"}}
  creationTimestamp: "2022-01-19T23:05:39Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 2
  name: test-conf-conn-backend-healthcheck
  namespace: test-conf-conn-negs
  resourceVersion: "24807"
  uid: 43b17d1d-7d94-483d-8111-a26579f63641
spec:
  checkIntervalSec: 10
  healthyThreshold: 2
  httpHealthCheck:
    port: 80
    proxyHeader: NONE
    requestPath: /
  location: global
  resourceID: test-conf-conn-backend-healthcheck
  timeoutSec: 5
  unhealthyThreshold: 2
status:
  conditions:
  - lastTransitionTime: "2022-01-19T23:05:51Z"
    message: The resource is up to date
    reason: UpToDate
    status: "True"
    type: Ready
  creationTimestamp: "2022-01-19T15:05:40.457-08:00"
  observedGeneration: 2
  selfLink: https://www.googleapis.com/compute/v1/projects/dspenard-playground/global/healthChecks/test-conf-conn-backend-healthcheck
  type: HTTP
