apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "neg-test-conf-conn-negs"}}}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"80":"neg-test-conf-conn-negs"},"zones":["us-central1-a","us-central1-b","us-central1-f"]}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"exposed_ports\": {\"80\":{\"name\": \"neg-test-conf-conn-negs\"}}}"},"labels":{"app":"echo"},"name":"test-conf-conn-negs-service","namespace":"test-conf-conn-negs"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"echo"},"type":"ClusterIP"}}
  creationTimestamp: "2022-01-19T22:14:41Z"
  labels:
    app: echo
  name: test-conf-conn-negs-service
  namespace: test-conf-conn-negs
  resourceVersion: "4759"
  uid: 066f24f7-b1b8-4d19-9dbd-c563e5a571d4
spec:
  clusterIP: 10.8.9.212
  clusterIPs:
  - 10.8.9.212
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
