apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeURLMap
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: dspenard-playground
    cnrm.cloud.google.com/state-into-spec: merge
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"compute.cnrm.cloud.google.com/v1beta1","kind":"ComputeURLMap","metadata":{"annotations":{},"labels":{"retry":"again"},"name":"test-conf-conn-url-map","namespace":"test-conf-conn-negs"},"spec":{"defaultService":{"backendServiceRef":{"name":"test-conf-conn-backend-service"}},"hostRule":[{"hosts":["*"],"pathMatcher":"allpaths"}],"location":"global","pathMatcher":[{"defaultService":{"backendServiceRef":{"name":"test-conf-conn-backend-service"}},"name":"allpaths","pathRule":[{"paths":["/echo/*"],"service":{"backendServiceRef":{"name":"test-conf-conn-backend-service"}}},{"paths":["/*"],"service":{"backendServiceRef":{"name":"test-conf-conn-backend-service"}}}]}]}}
  creationTimestamp: "2022-01-19T23:05:40Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 2
  labels:
    retry: again
  name: test-conf-conn-url-map
  namespace: test-conf-conn-negs
  resourceVersion: "38694"
  uid: 5c4d7a31-b246-4287-bac0-98764f48410c
spec:
  defaultService:
    backendServiceRef:
      name: test-conf-conn-backend-service
  hostRule:
  - hosts:
    - '*'
    pathMatcher: allpaths
  location: global
  pathMatcher:
  - defaultService:
      backendServiceRef:
        name: test-conf-conn-backend-service
    name: allpaths
    pathRule:
    - paths:
      - /echo/*
      service:
        backendServiceRef:
          name: test-conf-conn-backend-service
    - paths:
      - /*
      service:
        backendServiceRef:
          name: test-conf-conn-backend-service
  resourceID: test-conf-conn-url-map
status:
  conditions:
  - lastTransitionTime: "2022-01-19T23:41:29Z"
    message: reference ComputeBackendService test-conf-conn-negs/test-conf-conn-backend-service
      is not ready
    reason: DependencyNotReady
    status: "False"
    type: Ready
  creationTimestamp: "2022-01-19T15:06:06.904-08:00"
  fingerprint: ep7YP08Q1qg=
  mapId: 5140865020871387000
  observedGeneration: 2
  selfLink: https://www.googleapis.com/compute/v1/projects/dspenard-playground/global/urlMaps/test-conf-conn-url-map
