apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: dspenard-playground 
  name: dspenard-test-bucket-2
spec:
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7
